trigger:
- master

jobs:
- job: Ubuntu

  strategy:
    matrix:
      gcc8:
        CC: gcc-8
        CXX: g++-8
        LLVM_VERSION: 0
        PYTHON_VERSION: 3.9
        BENCHMARK: 1
      gcc9:
        CC: gcc-9
        CXX: g++-9
        LLVM_VERSION: 0
        PYTHON_VERSION: 3.10
      clang7:
        CC: clang-7
        CXX: clang++-7
        LLVM_VERSION: 7
        PYTHON_VERSION: 3.9
        DISABLE_TBB: 1
        DISABLE_XSIMD: 1
      clang9:
        CC: clang-9
        CXX: clang++-9
        LLVM_VERSION: 9
        PYTHON_VERSION: 3.9

  pool:
    vmImage: 'ubuntu-20.04'

  steps:
    - checkout: self

    - script: |
        sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
        if [[ $(LLVM_VERSION) != 0 ]]; then
          wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository "deb http://apt.llvm.org/$(UBUNTU_NAME)/ llvm-toolchain-${UBUNTU_NAME}-$(LLVM_VERSION) main"
          sudo apt-get update
          sudo apt-get install --no-install-suggests --no-install-recommends clang-$(LLVM_VERSION)
        elif [[ $(CXX) == g++-8 ]]; then
          sudo apt-get update
          sudo apt-get install --no-install-suggests --no-install-recommends $CXX
        fi
      displayName: "Install build toolchain"

    - bash: echo "##vso[task.prependpath]$CONDA/bin"
      displayName: "Add conda to PATH"

    - template: ./ci/unix_build.yml

- job: macOS

  strategy:
    matrix:
      macOS_11:
        PYTHON_VERSION: 3.9
        IMAGE_NAME: 'macOS-11'
        DISABLE_TBB: 1
      macOS_12:
        PYTHON_VERSION: 3.9
        IMAGE_NAME: 'macOS-12'
        DISABLE_TBB: 1

  pool:
    vmImage: $(IMAGE_NAME)

  variables:
    CC: clang
    CXX: clang++

  steps:
    - checkout: self

    - bash: |
        echo "##vso[task.prependpath]$CONDA/bin"
        sudo chown -R $USER $CONDA
      displayName: "Add conda to PATH"

    - template: ./ci/unix_build.yml