trigger:
- master

jobs:
- job: Ubuntu

  strategy:
    matrix:
      ubuntu_20_gcc10:
        CC: gcc-10
        CXX: g++-10
        LLVM_VERSION: 0
        IMAGE_NAME: 'ubuntu-20.04'
        PYTHON_VERSION: 3.9
        BENCHMARK: 1

      ubuntu_latest_gcc11:
        CC: gcc-11
        CXX: g++-11
        LLVM_VERSION: 0
        IMAGE_NAME: 'ubuntu-latest'
        PYTHON_VERSION: 3.10
        DISABLE_TBB: 1
        DISABLE_XSIMD: 1

      ubuntu_20_clang11:
        CC: clang-11
        CXX: clang++-11
        LLVM_VERSION: 11
        IMAGE_NAME: 'ubuntu-20.04'
        PYTHON_VERSION: 3.10

  pool:
    vmImage: $(IMAGE_NAME)

  steps:
    - checkout: self

    - script: |
        sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
        if [[ $(LLVM_VERSION) != 0 ]]; then
          wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository "deb http://apt.llvm.org/$(UBUNTU_NAME)/ llvm-toolchain-${UBUNTU_NAME}-$(LLVM_VERSION) main"
          sudo apt-get update
          sudo apt-get install --no-install-suggests --no-install-recommends clang-$(LLVM_VERSION)
        fi
      displayName: "Install build toolchain"

    - bash: echo "##vso[task.prependpath]$CONDA/bin"
      displayName: "Add conda to PATH"

    - template: ./ci/unix_build.yml

- job: macOS

  strategy:
    matrix:
      macOS_latest:
        PYTHON_VERSION: 3.10
        IMAGE_NAME: 'macOS-latest'
        DISABLE_TBB: 1  # worked on MacOS 12.6 with M1 chip
        DISABLE_XSIMD: 1

  pool:
    vmImage: $(IMAGE_NAME)

  variables:
    CC: clang
    CXX: clang++

  steps:
    - checkout: self

    - bash: |
        echo "##vso[task.prependpath]$CONDA/bin"
        sudo chown -R $USER $CONDA
      displayName: "Add conda to PATH"

    - template: ./ci/unix_build.yml