name: foamalgo
channels:
  - conda-forge
dependencies:
  - cmake>=3.13
  - tbb-devel=2021.4
  - xtensor=0.23.10
  - xsimd=7.6.0
  - xtensor-blas=0.19.2
  - numpy>=1.21.3
  - pybind11=2.8.1
  - xtensor-python=0.25.3